// Generated by CoffeeScript 1.3.3

dojo.provide('app.App');

dojo.require('app.Hash');

dojo.require('app.Menubar');

dojo.require('dijit.layout.BorderContainer');

dojo.require('dijit.layout.ContentPane');

dojo.declare('app.App', [], {
  YEAR: null,
  hash: null,
  components: [],
  constructor: function(YEAR) {
    this.inherited(arguments);
    this.YEAR = YEAR;
    this.hash = new app.Hash();
    console.log(this.hash);
    return this.setupLayout();
  },
  setupLayout: function() {
    $('body').append('<div id="layer"></div>');
    dojo.subscribe('app/App/layerFadeOut', this, function() {
      return $('#layer').fadeOut(250);
    });
    dojo.subscribe('app/App/layerFadeIn', this, function() {
      return $('#layer').show();
    });
    $('body').append('<div id="container"></div>');
    this.components.container = new dijit.layout.BorderContainer({
      design: 'headeline',
      style: 'width:100%;height:100%;padding:0;'
    }, 'container');
    this.components.container.addChild(this.components.menubar = new app.Menubar({
      id: 'menubar',
      region: 'top'
    }));
    this.components.container.addChild(this.components.contents = new dijit.layout.BorderContainer({
      id: 'contents',
      region: 'center',
      style: 'padding:2px 6px 6px;'
    }));
    return this.components.container.startup();
  }
});
