// Generated by CoffeeScript 1.3.3

dojo.provide('app.Bbs');

dojo.require("dijit._Widget");

dojo.require("dijit._Templated");

dojo.require("dijit.layout.BorderContainer");

dojo.require("dijit.layout.ContentPane");

dojo.declare('app.Bbs', [dijit._Widget, dijit._Templated], {
  widgetsInTemplate: true,
  templateString: dojo.cache('app', 'templates/Bbs.html'),
  constructor: function() {
    this.inherited(arguments);
    return console.log('app.Bbs->Constructor');
  },
  postCreate: function() {
    return console.log('app.Bbs->postCreate');
  }
});
