// Generated by CoffeeScript 1.3.3

dojo.provide('app.Common');

dojo.declare('app.Common', [], {
  _countSubscribe: 0,
  _registerTempSubscribe: function(func) {
    var h;
    if (!(this.app != null)) {
      alert('@app is undefined');
      console.log(this);
    }
    this._countSubscribe++;
    console.log('Common->registerSubscribe:', '/temp/' + this.app + '/' + this._countSubscribe);
    return h = dojo.subscribe('/temp/' + this.app + '/' + this._countSubscribe, this, function(data) {
      dojo.unsubscribe(h);
      return func.apply(this, [data]);
    });
  },
  _getHashData: function(func) {
    this._registerTempSubscribe(func);
    return dojo.publish('app/Hash/getHash', ['/temp/' + this.app + '/' + this._countSubscribe]);
  },
  _getTableData: function(table, func) {
    this._registerTempSubscribe(func);
    return dojo.publish('app/DataManager/getData', [table, '/temp/' + this.app + '/' + this._countSubscribe]);
  },
  _getUserData: function(func) {
    this._registerTempSubscribe(func);
    return dojo.publish('app/DataManager/getUserData', ['/temp/' + this.app + '/' + this._countSubscribe]);
  }
});
