// Generated by CoffeeScript 1.3.3

dojo.provide("app.Hash");

dojo.require("dojo.hash");

dojo.declare("app.Hash", [], {
  hash: null,
  constructor: function() {
    this.setSubscribe();
    if (dojo.hash() === '') {
      return dojo.publish('app/Hash/changeHash', [
        {
          mode: 'top'
        }
      ]);
    }
  },
  setSubscribe: function() {
    var h, handles;
    handles = [];
    handles.push(dojo.subscribe('/dojo/hashchange', this, this.onHashChange));
    handles.push(dojo.subscribe('app/Hash/changeHash', this, this.changeHash));
    return h = dojo.connect(this, 'uninitialize', this, function() {
      var handle, _i, _len, _results;
      dojo.disconnect(h);
      _results = [];
      for (_i = 0, _len = handles.length; _i < _len; _i++) {
        handle = handles[_i];
        _results.push(dojo.unsubscribe(handle));
      }
      return _results;
    });
  },
  onHashChange: function() {
    var i, tmp, _i, _len, _ref, _results;
    this.hash = {};
    _ref = dojo.hash().split("&");
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      if (i.indexOf("=") !== -1) {
        tmp = i.split('=');
        _results.push(this.hash[tmp[0]] = tmp[1]);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  },
  changeHash: function(status) {
    var hash, i, key, tmp, value, _i, _len, _ref;
    hash = {};
    _ref = dojo.hash().split('&');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      if (i.indexOf('=') !== -1) {
        tmp = i.split('=');
        hash[tmp[0]] = tmp[1];
      }
    }
    for (key in status) {
      value = status[key];
      hash[key] = value;
    }
    tmp = [];
    for (key in hash) {
      value = hash[key];
      tmp.push(key + '=' + value);
    }
    hash = tmp.join('&');
    return location.hash = hash;
  }
});
