// Generated by CoffeeScript 1.3.3

dojo.provide('app.Login');

dojo.require("dijit._Widget");

dojo.require("dijit._Templated");

dojo.require("dijit.layout.BorderContainer");

dojo.require("dijit.layout.ContentPane");

dojo.require("dijit.layout.AccordionContainer");

dojo.declare('app.Login', [dijit._Widget, dijit._Templated, app.Common], {
  app: 'app.Login',
  widgetsInTemplate: true,
  templateString: dojo.cache('app', 'templates/Login.html'),
  user: null,
  onSetupFlag: false,
  constructor: function() {
    this.inherited(arguments);
    return console.log('app.Login->Constructor');
  },
  postCreate: function() {
    this.inherited(arguments);
    return console.log('app.Login->postCreate');
  },
  onShow: function() {
    console.log('app.Login->onShow');
    return this._login(function(data) {
      if (!(data != null)) {
        return false;
      }
      this.user = data;
      return this.onSetup();
    });
  },
  onSetup: function() {
    if (this.onSetupFlag) {
      return false;
    }
    this.onSetupFlag = true;
    return new app.Div({
      topic: 'ログインメニュー：' + this.user.display_name + 'さん',
      body: "<div style='margin-bottom:12px;'>\n	</div>"
    }).placeAt(this.main.domNode).startup();
  }
});
