// Generated by CoffeeScript 1.3.3

dojo.provide("app.MenubarButton");

dojo.require("dijit.form.Button");

dojo.declare("app.MenubarButton", [dijit.form.Button], {
  normal: "#003d6c",
  selected: "#CC0000",
  postCreate: function() {
    this.inherited(arguments);
    return this.setColorType('normal');
  },
  setColorType: function(type) {
    return this.titleNode.style.color = this[type];
  }
});
