// Generated by CoffeeScript 1.3.3

dojo.provide("app.MenubarButton");

dojo.require("dijit.form.Button");

dojo.declare("app.MenubarButton", [dijit.form.Button], {
  enableColor: "#003d6c",
  nowColor: "#CC0000",
  disabledFlag: null,
  postCreate: function() {
    this.inherited(arguments);
    return this.titleNode.style.color = this.enableColor;
  },
  setNowButton: function() {
    if (this.dojoAttachPoint.indexOf(HASH.hash.mode) !== -1) {
      return this.titleNode.style.color = this.nowColor;
    } else {
      return this.setDisabled(this.disabledFlag);
    }
  },
  setDisabled: function(flag) {
    this.inherited(arguments);
    this.disabledFlag = flag;
    if (this.disabledFlag) {
      return this.titleNode.style.color = null;
    } else {
      return this.titleNode.style.color = this.enableColor;
    }
  }
});
