// Generated by CoffeeScript 1.3.3

dojo.provide('app.Post');

dojo.require('dijit._Widget');

dojo.require('dijit._Templated');

dojo.declare('app.Post', [dijit._Widget, dijit._Templated], {
  widgetsInTemplate: true,
  templateString: dojo.cache('app', 'templates/Post.html'),
  body: '',
  style: 'display:none;',
  constructor: function(data) {
    this.inherited(arguments);
    this.data = data;
    delete this.data.id;
    return this.data.created = this.data.created.split('-').join('/');
  },
  postCreate: function() {
    this.inherited(arguments);
    $(this.appDatetime).text(this.data.created);
    if (this.data.display_name != null) {
      return $(this.appUserName).text(this.data.display_name + ' (' + this.data.username + ')');
    } else {
      return $(this.appUserName).text('anonymous user');
    }
  },
  startup: function() {
    this.inherited(arguments);
    return $(this.top).fadeIn(200);
  }
});
